version: '2'

networks:
  default:
    driver: bridge

services:
  app:
      build:
        context: ./
        dockerfile: ./docker/Dockerfile
      ports:
        - 80:80
      networks:
        - default
      # Запускаем только после db
      depends_on:
        - db
      volumes:
        - "./:/var/www/app"

  db:
    image: mysql:5.7
    networks:
      - default
    ports:
      - "3336:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vi-test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
